-- Agrandissement de la banque de questions du quiz (0016) pour repousser le nombre de jours
-- sans répétition. Priorité à "difficile" (le goulot d'étranglement : 3 questions/jour).

insert into public.quiz_questions (category, difficulty, question, choices, correct_index, explanation) values

-- ===== SCORE (finales/matchs mythiques) =====
('score', 'easy', 'Quel a été le score de la finale de la Coupe du Monde 2022 au Qatar entre l''Argentine et la France ?', '["2-2 (tab 5-4)", "3-3 (tab 4-2)", "3-2", "2-1"]', 1, 'L''Argentine de Messi s''est imposée aux tirs au but après un match complètement fou.'),
('score', 'easy', 'Quel a été le score de la finale de la Coupe du Monde 2014, remportée par l''Allemagne face à l''Argentine ?', '["1-0", "2-1", "1-1 (tab)", "2-0"]', 0, 'Mario Götze a marqué le seul but de la rencontre en prolongation.'),
('score', 'easy', 'Quel a été le score de la finale de la Coupe du Monde 2010 entre l''Espagne et les Pays-Bas ?', '["2-1", "1-0", "1-1 (tab)", "3-1"]', 1, 'But d''Andrés Iniesta en prolongation, à Johannesburg.'),
('score', 'easy', 'Quel a été le score de la finale de la Coupe du Monde 2002 entre le Brésil et l''Allemagne ?', '["1-0", "3-1", "2-0", "2-1"]', 2, 'Doublé de Ronaldo pour le 5e titre du Brésil.'),
('score', 'easy', 'Quel a été le score de la finale de l''Euro 2024 entre l''Espagne et l''Angleterre ?', '["1-0", "2-1", "3-2", "2-0"]', 1, 'L''Espagne décroche un 4e titre européen.'),
('score', 'easy', 'Quel a été le score de la finale de l''Euro 2016 entre le Portugal et la France, pays hôte ?', '["1-0 (a.p.)", "2-1", "1-1 (tab)", "3-1"]', 0, 'But d''Eder en prolongation, sans Ronaldo blessé en début de match.'),
('score', 'easy', 'Quel a été le score de la finale de la Ligue des Champions 2023 entre Manchester City et l''Inter Milan ?', '["2-0", "1-0", "1-1 (tab)", "3-1"]', 1, 'But de Rodri, City remporte son premier titre européen.'),
('score', 'easy', 'Quel a été le score de la finale de la Ligue des Champions 2019 entre Liverpool et Tottenham ?', '["1-0", "3-0", "2-0", "2-1"]', 2, 'Buts de Salah et Origi, à Madrid.'),
('score', 'medium', 'Quel a été le score de la finale de la Coupe du Monde 1994, entre le Brésil et l''Italie ?', '["1-0", "0-0 (tab 3-2)", "2-1", "1-1 (tab)"]', 1, 'Roberto Baggio manque le tir au but décisif.'),
('score', 'medium', 'Quel a été le score de la finale de la Coupe du Monde 1990 entre l''Allemagne de l''Ouest et l''Argentine ?', '["1-0", "2-0", "2-1", "1-1 (tab)"]', 0, 'Penalty d''Andreas Brehme, à Rome.'),
('score', 'medium', 'Quel a été le score de la finale de la Coupe du Monde 1986 entre l''Argentine de Maradona et l''Allemagne de l''Ouest ?', '["2-1", "3-2", "4-1", "1-0"]', 1, 'Argentine 3-2 Allemagne, au Mexique.'),
('score', 'medium', 'Quel a été le score de la finale de la Coupe du Monde 1982 entre l''Italie et l''Allemagne de l''Ouest ?', '["3-1", "2-0", "1-0", "4-2"]', 0, 'Doublé de Paolo Rossi, meilleur buteur du tournoi.'),
('score', 'medium', 'Quel a été le score de la finale de la Coupe du Monde 1978 entre l''Argentine, pays hôte, et les Pays-Bas ?', '["2-1", "3-1 (a.p.)", "1-0", "2-2 (tab)"]', 1, 'Kempes marque deux fois, victoire argentine en prolongation.'),
('score', 'medium', 'Quel a été le score de la finale de l''Euro 2012 entre l''Espagne et l''Italie ?', '["2-0", "4-0", "3-1", "1-0"]', 1, 'Large victoire espagnole, doublé de David Silva et Torres.'),
('score', 'medium', 'Quel a été le score de la finale de l''Euro 2008 entre l''Espagne et l''Allemagne ?', '["1-0", "2-1", "2-0", "1-1 (tab)"]', 0, 'But de Fernando Torres, premier grand titre de cette génération espagnole.'),
('score', 'medium', 'Quel a été le score de la finale de l''Euro 2000 entre la France et l''Italie ?', '["2-1 (a.p.)", "1-0", "3-2", "2-0"]', 0, 'But en or de David Trezeguet en prolongation.'),
('score', 'medium', 'Quel a été le score de la finale de l''Euro 1996 entre l''Allemagne et la République tchèque ?', '["2-1 (a.p.)", "1-0", "3-1", "2-0"]', 0, 'But en or d''Oliver Bierhoff, à Wembley.'),
('score', 'medium', 'Quel a été le score de la finale de la Ligue des Champions 2022 entre le Real Madrid et Liverpool ?', '["1-0", "2-1", "2-0", "1-1 (tab)"]', 0, 'But de Vinícius Júnior, à Paris.'),
('score', 'medium', 'Quel a été le score de la finale de la Ligue des Champions 2014 entre le Real Madrid et l''Atlético Madrid ?', '["4-1 (a.p.)", "2-0", "3-2", "1-0"]', 0, 'Égalisation de Sergio Ramos dans les derniers instants, puis démonstration madrilène en prolongation ("La Décima").'),
('score', 'medium', 'Quel a été le score de la finale de la Ligue des Champions 2012 entre Chelsea et le Bayern Munich, à Munich ?', '["1-1 (tab 4-3)", "2-1", "1-0", "0-0 (tab)"]', 0, 'Égalisation de Drogba en fin de match, puis victoire aux tirs au but.'),
('score', 'medium', 'Quel a été le score de la finale de la Ligue des Champions 2011 entre le FC Barcelone et Manchester United, à Wembley ?', '["3-1", "2-0", "4-1", "1-0"]', 0, 'Buts de Pedro, Messi et Villa.'),
('score', 'medium', 'Quel a été le score de la finale de la Ligue des Champions 2009 entre le FC Barcelone et Manchester United, à Rome ?', '["2-0", "1-0", "3-1", "2-1"]', 0, 'Buts d''Eto''o et Messi.'),
('score', 'medium', 'Quel a été le score de la finale de l''Euro 2004, remportée-surprise par la Grèce face au pays hôte, le Portugal ?', '["1-0", "2-1", "1-1 (tab)", "2-0"]', 0, 'But de Charisteas de la tête.'),
('score', 'hard', 'Quel a été le score de la toute première finale de la Coupe du Monde, en 1930, entre l''Uruguay, pays hôte, et l''Argentine ?', '["4-2", "3-1", "2-1", "5-3"]', 0, 'L''Uruguay remporte le tout premier titre mondial, à Montevideo.'),
('score', 'hard', 'Quel a été le score de la finale de la Coupe du Monde 1934 entre l''Italie, pays hôte, et la Tchécoslovaquie ?', '["2-1 (a.p.)", "1-0", "3-2", "2-0"]', 0, null),
('score', 'hard', 'Quel a été le score de la finale de la Coupe du Monde 1938 entre l''Italie et la Hongrie ?', '["4-2", "3-1", "2-0", "5-2"]', 0, 'L''Italie conserve son titre.'),
('score', 'hard', 'Quel a été le score du dernier match de la Coupe du Monde 1950, resté célèbre sous le nom de "Maracanazo", entre l''Uruguay et le Brésil ?', '["2-1", "1-0", "3-2", "2-0"]', 0, 'Défaite traumatisante du Brésil à domicile, devant plus de 170 000 spectateurs au Maracanã.'),
('score', 'hard', 'Quel a été le score de la finale de la Coupe du Monde 1954, surnommée le "Miracle de Berne", entre l''Allemagne de l''Ouest et la Hongrie ?', '["3-2", "2-1", "4-2", "1-0"]', 0, 'La Hongrie de Puskás, grande favorite, s''incline en finale.'),
('score', 'hard', 'Quel a été le score de la finale de la Coupe du Monde 1958 entre le Brésil et la Suède, pays hôte ?', '["5-2", "3-1", "4-2", "2-0"]', 0, 'Premier titre mondial du Brésil, révélation d''un certain Pelé, 17 ans.'),
('score', 'hard', 'Quel a été le score de la finale de la Coupe du Monde 1962 entre le Brésil et la Tchécoslovaquie ?', '["3-1", "2-0", "4-2", "1-0"]', 0, null),
('score', 'hard', 'Quel a été le score de la finale de la Coupe du Monde 1970 entre le Brésil et l''Italie ?', '["4-1", "3-0", "2-1", "5-2"]', 0, 'Troisième titre mondial de Pelé, au Mexique.'),
('score', 'hard', 'Quel a été le score de la finale de la Coupe du Monde 1974 entre l''Allemagne de l''Ouest, pays hôte, et les Pays-Bas de Cruyff ?', '["2-1", "1-0", "3-2", "2-0"]', 0, null),
('score', 'hard', 'Quel a été le résultat de la finale de l''Euro 1976, restée célèbre pour le penalty "Panenka" décisif, entre la Tchécoslovaquie et l''Allemagne de l''Ouest ?', '["2-2 (tab 5-3)", "1-0", "3-1", "1-1 (tab)"]', 0, 'Antonín Panenka marque le tir au but victorieux d''une célèbre "pichenette".'),
('score', 'hard', 'Quel a été le score de la finale de l''Euro 1988 entre les Pays-Bas et l''URSS, marquée par une volée légendaire de Marco van Basten ?', '["2-0", "1-0", "3-1", "2-1"]', 0, null),
('score', 'hard', 'Quel a été le score de la finale de l''Euro 1992, remportée-surprise par le Danemark (repêché tardivement) face à l''Allemagne ?', '["2-0", "1-0", "3-2", "1-1 (tab)"]', 0, 'Le Danemark, appelé en dernière minute suite à l''exclusion de la Yougoslavie, crée la sensation.'),
('score', 'hard', 'Quel a été le score de la toute première finale de Coupe d''Europe des clubs champions, en 1960, entre le Real Madrid et l''Eintracht Francfort ?', '["7-3", "5-2", "4-1", "6-3"]', 0, 'Un festival offensif à Hampden Park, avec un quadruplé de Puskás et un triplé de Di Stéfano.'),
('score', 'hard', 'Quel a été le score de la finale de la Coupe d''Europe des clubs champions 1968 entre Manchester United et Benfica ?', '["4-1 (a.p.)", "2-0", "3-1", "1-0"]', 0, 'Premier titre européen d''un club anglais, dix ans après le drame de Munich.'),

-- ===== PLAYER_CAREER (parcours de clubs, dans l''ordre) =====
('player_career', 'easy', 'Cet Argentin est passé, dans cet ordre, par Boca Juniors, le FC Barcelone puis le Napoli. Qui est-il ?', '["Diego Maradona", "Gabriel Batistuta", "Mario Kempes", "Diego Simeone"]', 0, null),
('player_career', 'easy', 'Ce Brésilien, triple champion du monde, n''a joué que pour deux clubs dans toute sa carrière : Santos puis le New York Cosmos. Qui est-il ?', '["Garrincha", "Pelé", "Zico", "Jairzinho"]', 1, null),
('player_career', 'easy', 'Cet Anglais est passé, dans cet ordre, par Manchester United, le Real Madrid, LA Galaxy puis le Paris Saint-Germain. Qui est-il ?', '["Michael Owen", "Steven Gerrard", "David Beckham", "Rio Ferdinand"]', 2, null),
('player_career', 'easy', 'Ce Français est passé, dans cet ordre, par l''AS Monaco, la Juventus, Arsenal puis le FC Barcelone. Qui est-il ?', '["Nicolas Anelka", "Thierry Henry", "Sylvain Wiltord", "David Trezeguet"]', 1, null),
('player_career', 'easy', 'Ce Brésilien est passé, dans cet ordre, par le Grêmio, le Paris Saint-Germain, le FC Barcelone puis l''AC Milan. Qui est-il ?', '["Ronaldinho", "Kaká", "Robinho", "Adriano"]', 0, null),
('player_career', 'easy', 'Cet Anglais est passé, dans cet ordre, par Liverpool, le Real Madrid, Newcastle United puis Manchester United. Qui est-il ?', '["Michael Owen", "Steven Gerrard", "Jamie Carragher", "Emile Heskey"]', 0, null),
('player_career', 'easy', 'Cet Ivoirien est passé, dans cet ordre, par l''Olympique de Marseille, Chelsea puis Galatasaray. Qui est-il ?', '["Yaya Touré", "Didier Drogba", "Kolo Touré", "Salomon Kalou"]', 1, null),
('player_career', 'easy', 'Ce Néerlandais, auteur d''une volée mythique en finale de l''Euro 1988, n''a joué que pour l''Ajax puis l''AC Milan. Qui est-il ?', '["Dennis Bergkamp", "Marco van Basten", "Ruud Gullit", "Frank Rijkaard"]', 1, null),
('player_career', 'easy', 'Cet Italien est passé, dans cet ordre, par Naples, Parme puis Chelsea. Qui est-il ?', '["Gianfranco Zola", "Roberto Baggio", "Alessandro Del Piero", "Filippo Inzaghi"]', 0, null),
('player_career', 'easy', 'Cet Allemand a joué au Bayern Munich puis terminé sa carrière au New York Cosmos, aux côtés de Pelé. Qui est-il ?', '["Franz Beckenbauer", "Karl-Heinz Rummenigge", "Lothar Matthäus", "Gerd Müller"]', 0, null),
('player_career', 'medium', 'Ce Brésilien est passé, dans cet ordre, par São Paulo, l''AC Milan puis le Real Madrid. Qui est-il ?', '["Kaká", "Ronaldinho", "Robinho", "Pato"]', 0, null),
('player_career', 'medium', 'Surnommé "Il Fenomeno", ce Brésilien est passé, dans cet ordre, par le PSV Eindhoven, le FC Barcelone, l''Inter Milan puis le Real Madrid. Qui est-il ?', '["Romário", "Ronaldo Nazário", "Rivaldo", "Adriano"]', 1, null),
('player_career', 'medium', 'Ce milieu italien est passé, dans cet ordre, par l''Inter Milan, l''AC Milan puis la Juventus. Qui est-il ?', '["Andrea Pirlo", "Gennaro Gattuso", "Daniele De Rossi", "Andrea Barzagli"]', 0, null),
('player_career', 'medium', 'Cet Anglais est passé, dans cet ordre, par Everton, Manchester United puis DC United. Qui est-il ?', '["Wayne Rooney", "Michael Owen", "Jermain Defoe", "Andy Cole"]', 0, null),
('player_career', 'medium', 'Cet Anglais est passé, dans cet ordre, par West Ham United, Chelsea puis Manchester City. Qui est-il ?', '["Joe Cole", "Frank Lampard", "John Terry", "Ashley Cole"]', 1, null),
('player_career', 'medium', 'Ce Camerounais est passé, dans cet ordre, par Mallorca, le FC Barcelone, l''Inter Milan puis Chelsea. Qui est-il ?', '["Samuel Eto''o", "Roger Milla", "Rigobert Song", "Patrick Mboma"]', 0, null),
('player_career', 'medium', 'Ce Néerlandais est passé, dans cet ordre, par le Feyenoord, Arsenal puis Manchester United. Qui est-il ?', '["Robin van Persie", "Dennis Bergkamp", "Ruud van Nistelrooy", "Klaas-Jan Huntelaar"]', 0, null),
('player_career', 'medium', 'Ce Néerlandais est passé, dans cet ordre, par l''Ajax, l''Inter Milan puis Arsenal. Qui est-il ?', '["Dennis Bergkamp", "Robin van Persie", "Patrick Kluivert", "Marc Overmars"]', 0, null),
('player_career', 'medium', 'Ce Néerlandais, longtemps meilleur buteur de l''histoire de la Ligue des Champions, est passé, dans cet ordre, par le PSV Eindhoven, Manchester United puis le Real Madrid. Qui est-il ?', '["Ruud van Nistelrooy", "Patrick Kluivert", "Robin van Persie", "Klaas-Jan Huntelaar"]', 0, null),
('player_career', 'medium', 'Ce gardien néerlandais est passé, dans cet ordre, par l''Ajax, la Juventus, Fulham puis Manchester United. Qui est-il ?', '["Edwin van der Sar", "Jerzy Dudek", "André Onana", "Maarten Stekelenburg"]', 0, null),
('player_career', 'medium', 'Ce Portugais, au centre d''un transfert record du Barça au Real Madrid en 2000, est passé, dans cet ordre, par le Sporting CP, le FC Barcelone, le Real Madrid puis l''Inter Milan. Qui est-il ?', '["Luís Figo", "Rui Costa", "Deco", "Nani"]', 0, null),
('player_career', 'medium', 'Ce Brésilien est passé, dans cet ordre, par le Deportivo La Corogne, le FC Barcelone puis l''AC Milan. Qui est-il ?', '["Rivaldo", "Romário", "Ronaldinho", "Denilson"]', 0, null),
('player_career', 'medium', 'Ce Libérien, seul joueur africain à avoir remporté le Ballon d''or, est passé, dans cet ordre, par l''AS Monaco, le Paris Saint-Germain, l''AC Milan puis Chelsea. Qui est-il ?', '["George Weah", "Didier Drogba", "Samuel Eto''o", "Yaya Touré"]', 0, 'George Weah, Ballon d''or 1995, est aussi devenu président du Liberia.'),
('player_career', 'medium', 'Cet Italien, surnommé "Il Divin Codino", est passé, dans cet ordre, par la Fiorentina, la Juventus puis l''AC Milan. Qui est-il ?', '["Roberto Baggio", "Alessandro Del Piero", "Gianluca Vialli", "Salvatore Schillaci"]', 0, null),
('player_career', 'medium', 'Ce Néerlandais est passé, dans cet ordre, par le PSV Eindhoven, l''AC Milan puis Chelsea. Qui est-il ?', '["Ruud Gullit", "Frank Rijkaard", "Marco van Basten", "Clarence Seedorf"]', 0, null),
('player_career', 'medium', 'Cet Allemand est passé, dans cet ordre, par le Bayer Leverkusen, le Bayern Munich puis Chelsea. Qui est-il ?', '["Michael Ballack", "Lothar Matthäus", "Mehmet Scholl", "Oliver Kahn"]', 0, null),
('player_career', 'medium', 'Ce Néerlandais est passé, dans cet ordre, par l''Ajax, le FC Barcelone puis le Feyenoord. Qui est-il ?', '["Johan Cruyff", "Marco van Basten", "Dennis Bergkamp", "Frank de Boer"]', 0, 'Son passage de l''Ajax au Barça, puis son retour tardif chez le rival Feyenoord, ont marqué les esprits.'),
('player_career', 'hard', 'Seul joueur à avoir remporté la Ligue des Champions avec trois clubs différents, ce Néerlandais est passé, dans cet ordre, par l''Ajax, le Real Madrid, l''Inter Milan puis l''AC Milan. Qui est-il ?', '["Clarence Seedorf", "Edgar Davids", "Patrick Kluivert", "Jaap Stam"]', 0, null),
('player_career', 'hard', 'Cet Allemand est passé, dans cet ordre, par le VfB Stuttgart, l''Inter Milan, Tottenham puis le Bayern Munich. Qui est-il ?', '["Jürgen Klinsmann", "Lothar Matthäus", "Rudi Völler", "Andreas Brehme"]', 0, null),
('player_career', 'hard', 'Cet Allemand, capitaine lors de la victoire en Coupe du Monde 1990, est passé, dans cet ordre, par le Borussia Mönchengladbach, le Bayern Munich puis l''Inter Milan. Qui est-il ?', '["Lothar Matthäus", "Jürgen Klinsmann", "Andreas Brehme", "Pierre Littbarski"]', 0, null),
('player_career', 'hard', 'Cet Allemand est passé, dans cet ordre, par le Bayern Munich puis l''Inter Milan, avant de terminer sa carrière au Servette. Qui est-il ?', '["Karl-Heinz Rummenigge", "Paul Breitner", "Uli Hoeness", "Franz Beckenbauer"]', 0, null),
('player_career', 'hard', 'Ce Néerlandais est passé, dans cet ordre, par l''Ajax puis l''AC Milan, avant un bref retour à l''Ajax en fin de carrière. Qui est-il ?', '["Frank Rijkaard", "Ronald Koeman", "Marco van Basten", "Aron Winter"]', 0, null),
('player_career', 'hard', 'Ce défenseur italien, capitaine emblématique, n''a joué que pour un seul club durant toute sa carrière professionnelle : l''AC Milan. Qui est-il ?', '["Paolo Maldini", "Franco Baresi", "Alessandro Costacurta", "Fabio Cannavaro"]', 0, null),
('player_career', 'hard', 'Cet attaquant italien, capitaine et légende de l''AS Roma, n''a joué que pour ce seul club durant toute sa carrière professionnelle. Qui est-il ?', '["Francesco Totti", "Daniele De Rossi", "Vincent Candela", "Antonio Cassano"]', 0, null),
('player_career', 'hard', 'Ce milieu espagnol, figure du FC Barcelone, a terminé sa carrière au Qatar, à Al Sadd. Qui est-il ?', '["Xavi Hernández", "Andrés Iniesta", "Sergio Busquets", "Carles Puyol"]', 0, null),
('player_career', 'hard', 'Ce milieu espagnol, auteur du but de la victoire en finale de la Coupe du Monde 2010, a terminé sa carrière au Japon, au Vissel Kobe. Qui est-il ?', '["Andrés Iniesta", "Xavi Hernández", "Cesc Fàbregas", "David Silva"]', 0, null),
('player_career', 'hard', 'Ce défenseur espagnol, capitaine emblématique du FC Barcelone, n''a joué que pour ce seul club durant toute sa carrière professionnelle. Qui est-il ?', '["Carles Puyol", "Gerard Piqué", "Sergio Busquets", "Javier Mascherano"]', 0, null),
('player_career', 'hard', 'Ce gardien espagnol, champion du monde 2010, est passé, dans cet ordre, par le Real Madrid puis le FC Porto. Qui est-il ?', '["Iker Casillas", "Víctor Valdés", "David de Gea", "Pepe Reina"]', 0, null),
('player_career', 'hard', 'Cet attaquant espagnol, légende du Real Madrid, a terminé sa carrière en Allemagne, à Schalke 04. Qui est-il ?', '["Raúl González", "Fernando Morientes", "Fernando Torres", "David Villa"]', 0, null),
('player_career', 'hard', 'Ce milieu anglais, capitaine emblématique de Liverpool, a terminé sa carrière aux États-Unis, à LA Galaxy. Qui est-il ?', '["Steven Gerrard", "Frank Lampard", "Paul Scholes", "Jamie Carragher"]', 0, null),
('player_career', 'hard', 'Ce défenseur anglais, capitaine de Chelsea pendant plus d''une décennie, n''a joué que pour ce seul club durant l''essentiel de sa carrière. Qui est-il ?', '["John Terry", "Frank Lampard", "Ashley Cole", "Petr Čech"]', 0, null),
('player_career', 'hard', 'Cet attaquant italien, capitaine et symbole de la Juventus pendant deux décennies, n''a joué que pour ce seul club durant l''essentiel de sa carrière. Qui est-il ?', '["Alessandro Del Piero", "Roberto Baggio", "Gianluigi Buffon", "Pavel Nedvěd"]', 0, null),
('player_career', 'hard', 'Ce Bulgare, Ballon d''or 1994, est passé, dans cet ordre, par le CSKA Sofia, le FC Barcelone puis le Parme. Qui est-il ?', '["Hristo Stoichkov", "Krasimir Balakov", "Emil Kostadinov", "Yordan Letchkov"]', 0, null),
('player_career', 'hard', 'Ce Brésilien, l''un des "trois Ronaldo/Romário" de la génération dorée, est passé, dans cet ordre, par Vasco da Gama, le PSV Eindhoven puis le FC Barcelone. Qui est-il ?', '["Romário", "Bebeto", "Careca", "Zico"]', 0, null),

-- ===== TRIVIA (culture générale) =====
('trivia', 'easy', 'Dans quel pays les règles modernes du football ont-elles été codifiées, en 1863, avec la création de la première Football Association ?', '["France", "Angleterre", "Écosse", "Brésil"]', 1, null),
('trivia', 'easy', 'Combien de minutes durent, au total, les deux mi-temps des prolongations d''un match à élimination directe ?', '["20 minutes", "30 minutes", "15 minutes", "45 minutes"]', 1, 'Deux périodes de 15 minutes.'),
('trivia', 'easy', 'Comment se nomme la principale compétition de clubs sud-américaine, équivalent de la Ligue des Champions ?', '["Copa América", "Copa Libertadores", "Copa del Rey", "Copa Sudamericana"]', 1, null),
('trivia', 'easy', 'Quel pays a organisé la Coupe du Monde 2010, la première disputée sur le continent africain ?', '["Maroc", "Égypte", "Afrique du Sud", "Nigeria"]', 2, null),
('trivia', 'easy', 'Quel pays d''Asie a co-organisé la Coupe du Monde 2002 avec la Corée du Sud ?', '["Chine", "Japon", "Thaïlande", "Vietnam"]', 1, null),
('trivia', 'easy', 'Combien de fois la France a-t-elle remporté la Coupe du Monde, avant l''édition 2026 ?', '["1 fois", "2 fois", "3 fois", "0 fois"]', 1, '1998 et 2018.'),
('trivia', 'easy', 'Dans quel stade se joue traditionnellement la finale de la Coupe d''Angleterre (FA Cup) ?', '["Old Trafford", "Wembley Stadium", "Emirates Stadium", "Stamford Bridge"]', 1, null),
('trivia', 'easy', 'Quelle est la couleur traditionnelle du maillot domicile de l''équipe du Brésil ?', '["Vert", "Bleu", "Jaune", "Blanc"]', 2, null),
('trivia', 'easy', 'Quelles sont les couleurs traditionnelles du maillot de l''équipe d''Argentine ?', '["Vert et blanc", "Bleu ciel et blanc, rayé", "Bleu marine uni", "Rouge et blanc"]', 1, null),
('trivia', 'easy', 'Quel club évolue traditionnellement au Parc des Princes, à Paris ?', '["Racing Club de France", "Paris Saint-Germain", "Paris FC", "Red Star"]', 1, null),
('trivia', 'easy', 'Quelle sélection nationale est surnommée "les Diables Rouges" ?', '["Belgique", "Autriche", "Suisse", "Pays de Galles"]', 0, null),
('trivia', 'easy', 'Quelle sélection nationale est surnommée "la Roja" ?', '["Portugal", "Espagne", "Chili", "Pérou"]', 1, null),
('trivia', 'easy', 'Quelle sélection nationale est surnommée "les Three Lions" ?', '["Écosse", "Pays de Galles", "Angleterre", "Irlande"]', 2, null),
('trivia', 'easy', 'Quelle sélection nationale est surnommée "les Oranje" ?', '["Belgique", "Pays-Bas", "Luxembourg", "Suède"]', 1, null),
('trivia', 'easy', 'Quelle sélection nationale est surnommée "la Seleção" ?', '["Argentine", "Uruguay", "Brésil", "Portugal"]', 2, null),
('trivia', 'easy', 'Quelle association gouverne le football à l''échelle mondiale ?', '["UEFA", "FIFA", "CIO", "IFAB"]', 1, null),
('trivia', 'easy', 'Quelle association gouverne le football à l''échelle du continent européen ?', '["FIFA", "UEFA", "CAF", "CONMEBOL"]', 1, null),
('trivia', 'easy', 'Comment appelle-t-on la grande surface devant les buts, où une faute donne lieu à un penalty ?', '["La surface de réparation", "La zone neutre", "Le rectangle d''or", "La surface technique"]', 0, null),
('trivia', 'easy', 'Combien de temps un joueur exclu (carton rouge) laisse-t-il son équipe en infériorité numérique ?', '["10 minutes", "Jusqu''à la mi-temps", "Le reste du match", "5 minutes"]', 2, null),
('trivia', 'medium', 'En quelle année la FIFA a-t-elle été fondée ?', '["1930", "1904", "1863", "1950"]', 1, 'Fondée à Paris par sept fédérations européennes.'),
('trivia', 'medium', 'Combien de matchs compte une phase de groupes de 4 équipes où chacune affronte toutes les autres une fois ?', '["4", "6", "8", "5"]', 1, null),
('trivia', 'medium', 'Quel est le diamètre approximatif, en centimètres, d''un ballon de football réglementaire (taille 5) ?', '["15 cm", "18 cm", "22 cm", "28 cm"]', 2, null),
('trivia', 'medium', 'Combien de fois l''Italie a-t-elle remporté la Coupe du Monde, avant l''édition 2026 ?', '["2 fois", "3 fois", "4 fois", "5 fois"]', 2, '1934, 1938, 1982 et 2006.'),
('trivia', 'medium', 'Combien de fois l''Allemagne (RFA incluse) a-t-elle remporté la Coupe du Monde, avant l''édition 2026 ?', '["3 fois", "4 fois", "2 fois", "5 fois"]', 1, '1954, 1974, 1990 et 2014.'),
('trivia', 'medium', 'Combien de fois l''Argentine a-t-elle remporté la Coupe du Monde, avant l''édition 2026 ?', '["2 fois", "3 fois", "4 fois", "1 fois"]', 1, '1978, 1986 et 2022.'),
('trivia', 'medium', 'Quel est le surnom catalan du FC Barcelone, signifiant "plus qu''un club" ?', '["Més que un club", "El més gran", "Blaugrana per sempre", "La casa gran"]', 0, null),
('trivia', 'medium', 'Comment se nomme le stade du FC Barcelone ?', '["Santiago Bernabéu", "Camp Nou", "Metropolitano", "Mestalla"]', 1, null),
('trivia', 'medium', 'Comment se nomme le stade du Real Madrid ?', '["Camp Nou", "Wanda Metropolitano", "Santiago Bernabéu", "Vicente Calderón"]', 2, null),
('trivia', 'medium', 'Comment se nomme le stade de Manchester United, surnommé "le théâtre des rêves" ?', '["Anfield", "Old Trafford", "Etihad Stadium", "Stamford Bridge"]', 1, null),
('trivia', 'medium', 'Comment se nomme le stade du Bayern Munich ?', '["Signal Iduna Park", "Allianz Arena", "Veltins-Arena", "Olympiastadion"]', 1, null),
('trivia', 'medium', 'Combien de fois la France a-t-elle remporté le Championnat d''Europe des Nations (Euro), avant l''édition 2024 ?', '["1 fois", "2 fois", "3 fois", "0 fois"]', 1, '1984 et 2000.'),
('trivia', 'medium', 'Combien de fois l''Espagne a-t-elle remporté le Championnat d''Europe des Nations (Euro), en comptant le titre 2024 ?', '["2 fois", "3 fois", "4 fois", "5 fois"]', 2, '1964, 2008, 2012 et 2024.'),
('trivia', 'medium', 'Quel système tactique défensif, emblématique du football italien des années 1960-70, repose sur un verrou défensif et un libéro ?', '["Le tiki-taka", "Le catenaccio", "Le kick and rush", "Le gegenpressing"]', 1, null),
('trivia', 'hard', 'Dans quelle ville, en Écosse, se trouve le stade Hampden Park, qui a accueilli plusieurs finales de Coupe d''Europe ?', '["Édimbourg", "Glasgow", "Aberdeen", "Dundee"]', 1, null),
('trivia', 'hard', 'Comment se nomme le stade du Borussia Dortmund, célèbre pour son immense tribune surnommée le "Mur Jaune" ?', '["Veltins-Arena", "Signal Iduna Park", "RheinEnergieStadion", "Volksparkstadion"]', 1, null),
('trivia', 'hard', 'Comment se nomme le stade de la Juventus, inauguré en 2011 ?', '["San Siro", "Allianz Stadium", "Stadio Olimpico", "Artemio Franchi"]', 1, null),
('trivia', 'hard', 'Quelle sélection nationale est surnommée "la Nati" ?', '["Autriche", "Suisse", "Slovénie", "Slovaquie"]', 1, null),
('trivia', 'hard', 'Combien de fois l''Allemagne (RFA incluse) a-t-elle remporté le Championnat d''Europe des Nations (Euro), avant l''édition 2024 ?', '["2 fois", "3 fois", "4 fois", "1 fois"]', 1, '1972, 1980 et 1996.'),
('trivia', 'hard', 'Quelle sélection a remporté le tout premier Championnat d''Europe des Nations, en 1960 ?', '["Yougoslavie", "URSS", "Tchécoslovaquie", "Hongrie"]', 1, null),
('trivia', 'hard', 'Dans quelle ville suisse se trouve le siège de la FIFA ?', '["Genève", "Berne", "Zurich", "Nyon"]', 2, null),
('trivia', 'hard', 'Dans quelle ville suisse se trouve le siège de l''UEFA ?', '["Zurich", "Genève", "Nyon", "Lausanne"]', 2, null),
('trivia', 'hard', 'Quel est le nom du trophée remis à la sélection championne du monde depuis l''édition 1974 ?', '["La Coupe Jules-Rimet", "Le Trophée de la Coupe du Monde de la FIFA", "La Coupe d''Or", "Le Trophée des Nations"]', 1, 'L''originale Coupe Jules-Rimet, remise jusqu''en 1970, a été définitivement offerte au Brésil après son 3e titre.'),

-- ===== VINTAGE_JERSEY (identité kit / couleurs historiques) =====
('vintage_jersey', 'easy', 'Quelle sélection porte traditionnellement un maillot domicile entièrement jaune, avec un short bleu ?', '["Colombie", "Brésil", "Suède", "Roumanie"]', 1, null),
('vintage_jersey', 'easy', 'Quelle sélection porte traditionnellement un maillot rayé bleu ciel et blanc ?', '["Uruguay", "Argentine", "Suède", "Islande"]', 1, null),
('vintage_jersey', 'easy', 'Quelle sélection est surnommée "les Azzurri" en référence à son maillot bleu ?', '["Italie", "France", "Grèce", "Slovénie"]', 0, null),
('vintage_jersey', 'easy', 'Quelle sélection porte traditionnellement un maillot domicile entièrement blanc ?', '["Belgique", "Croatie", "Allemagne", "Espagne"]', 2, null),
('vintage_jersey', 'easy', 'Quelle sélection porte traditionnellement un maillot domicile entièrement bleu ?', '["Italie", "France", "Grèce", "Serbie"]', 1, null),
('vintage_jersey', 'easy', 'Quelle sélection porte traditionnellement un maillot orange vif, unique dans le paysage international ?', '["Pays-Bas", "Belgique", "Luxembourg", "Ukraine"]', 0, null),
('vintage_jersey', 'easy', 'Quelle sélection porte traditionnellement un maillot domicile rouge ?', '["Portugal", "Espagne", "Norvège", "Autriche"]', 1, null),
('vintage_jersey', 'easy', 'Quelle sélection porte traditionnellement un maillot vert ?', '["Mexique", "Bolivie", "Arabie saoudite", "Cameroun"]', 0, null),
('vintage_jersey', 'easy', 'Quel club est associé à un maillot rayé horizontalement rouge et noir, surnommé les "rossoneri" ?', '["Inter Milan", "AC Milan", "AS Roma", "Torino"]', 1, null),
('vintage_jersey', 'easy', 'Quel club est associé à un maillot rayé noir et blanc, surnommé les "bianconeri" ?', '["AC Milan", "Juventus", "Inter Milan", "Bologne"]', 1, null),
('vintage_jersey', 'medium', 'Quelle sélection porte traditionnellement un maillot rouge et vert, aux couleurs de son drapeau national ?', '["Portugal", "Italie", "Mexique", "Bulgarie"]', 0, null),
('vintage_jersey', 'medium', 'Quelle sélection sud-américaine, souvent qualifiée de "céleste", porte un maillot bleu ciel ?', '["Argentine", "Uruguay", "Paraguay", "Équateur"]', 1, null),
('vintage_jersey', 'medium', 'Quelle sélection porte un maillot à damier rouge et blanc, très reconnaissable ?', '["Serbie", "Croatie", "Pologne", "Autriche"]', 1, null),
('vintage_jersey', 'medium', 'Quel club est associé à un maillot rayé bleu et grenat, surnommé "blaugrana" ?', '["Espanyol", "FC Barcelone", "Valence", "Séville"]', 1, null),
('vintage_jersey', 'medium', 'Quel club anglais porte traditionnellement un maillot bleu roi ?', '["Manchester City", "Chelsea", "Everton", "Leicester City"]', 1, null),
('vintage_jersey', 'medium', 'Quel club anglais porte traditionnellement un maillot rouge, et est surnommé les "Red Devils" ?', '["Liverpool", "Manchester United", "Arsenal", "Nottingham Forest"]', 1, null),
('vintage_jersey', 'medium', 'Quel club argentin porte un maillot bleu barré d''une large bande horizontale jaune ?', '["River Plate", "Boca Juniors", "Racing Club", "Independiente"]', 1, null),
('vintage_jersey', 'medium', 'Quel club anglais est associé à un maillot rayé noir et blanc, et surnommé "les Magpies" (les pies) ?', '["Newcastle United", "West Bromwich Albion", "Notts County", "Grimsby Town"]', 0, null),
('vintage_jersey', 'medium', 'Quel club italien porte un maillot rouge et orangé, et évolue au Stadio Olimpico ?', '["Lazio", "AS Roma", "Fiorentina", "Torino"]', 1, null),
('vintage_jersey', 'hard', 'Quel club argentin porte un maillot blanc barré d''une bande diagonale rouge ?', '["Boca Juniors", "River Plate", "San Lorenzo", "Vélez Sarsfield"]', 1, null),
('vintage_jersey', 'hard', 'Quel club néerlandais porte traditionnellement un maillot rouge et blanc à bandes horizontales ?', '["PSV Eindhoven", "Feyenoord", "AZ Alkmaar", "FC Utrecht"]', 1, null),
('vintage_jersey', 'hard', 'Quel club portugais porte un maillot vert et blanc, à bandes horizontales ?', '["Benfica", "Sporting CP", "FC Porto", "Vitória Guimarães"]', 1, null),
('vintage_jersey', 'hard', 'Quel club allemand porte un maillot jaune et noir, et son stade est surnommé "le chaudron jaune" ?', '["Bayern Munich", "Borussia Dortmund", "Schalke 04", "Hambourg SV"]', 1, null),
('vintage_jersey', 'hard', 'Quel club écossais porte un maillot vert et blanc, rival historique des Rangers dans le "Old Firm" ?', '["Celtic Glasgow", "Aberdeen", "Hearts of Midlothian", "Hibernian"]', 0, null),
('vintage_jersey', 'hard', 'Quel club espagnol, basé au Pays basque, porte un maillot rayé rouge et blanc ?', '["Real Sociedad", "Athletic Bilbao", "Deportivo Alavés", "Eibar"]', 1, null);
